import { mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { parseSolidity } from './ast.ts';
import { contractsOf, functionsOf } from './ast.ts';
import { typeNameToString, isFuzzableElementary, needsMemoryLocation } from './typeutil.ts';

export interface FuzzGenOptions {
  filePath: string;
  contractName?: string;
  outDir?: string;
}

export interface FuzzGenResult {
  outPath: string;
  contractName: string;
  fuzzedFunctions: string[];
  skippedFunctions: string[];
}

/** Picks an instance-variable name that can't collide with any function's own parameter names. */
function pickInstanceVarName(fns: any[]): string {
  const used = new Set<string>();
  for (const fn of fns) {
    for (const p of fn.parameters ?? []) {
      if (p?.name) used.add(p.name);
    }
  }
  const candidates = ['target', '_target', '__target', 'auditkitTarget'];
  return candidates.find((c) => !used.has(c)) ?? `auditkitTarget${Date.now()}`;
}

function paramList(params: any[]): { signature: string; names: string[] } {
  const names: string[] = [];
  const parts = params.map((p, i) => {
    const t = typeNameToString(p.typeName);
    const name = p.name || `arg${i}`;
    names.push(name);
    const loc = needsMemoryLocation(t) ? ' memory' : '';
    return `${t}${loc} ${name}`;
  });
  return { signature: parts.join(', '), names };
}

export async function generateFuzzTest(opts: FuzzGenOptions): Promise<FuzzGenResult> {
  const source = await Bun.file(opts.filePath).text();
  const ast = parseSolidity(source, opts.filePath);
  const contracts = contractsOf(ast).filter((c: any) => c.kind === 'contract');
  if (contracts.length === 0) throw new Error(`no contract definitions found in ${opts.filePath}`);

  const contract = opts.contractName
    ? contracts.find((c: any) => c.name === opts.contractName)
    : contracts[0];
  if (!contract) throw new Error(`contract '${opts.contractName}' not found in ${opts.filePath}`);

  const outDir = opts.outDir ?? 'test/fuzz';
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, `${contract.name}.fuzz.t.sol`);
  const importPath = relative(outDir, opts.filePath).split('\\').join('/');

  const fns = functionsOf(contract).filter(
    (fn: any) =>
      fn.name &&
      (fn.visibility === 'public' || fn.visibility === 'external' || fn.visibility === 'default')
  );
  const instanceVar = pickInstanceVarName(fns);

  const ctor = functionsOf(contract).find((fn: any) => fn.isConstructor);
  const ctorArgsComment = ctor
    ? paramList(ctor.parameters ?? []).names.map((n) => `/* ${n} */`).join(', ')
    : '';

  const fuzzedFunctions: string[] = [];
  const skippedFunctions: string[] = [];
  const testBlocks: string[] = [];

  for (const fn of fns) {
    const params = fn.parameters ?? [];
    const allFuzzable = params.every((p: any) => isFuzzableElementary(p.typeName));
    if (!allFuzzable) {
      skippedFunctions.push(fn.name);
      continue;
    }
    fuzzedFunctions.push(fn.name);
    const { signature, names } = paramList(params);
    const callArgs = names.join(', ');
    testBlocks.push(
      `    function testFuzz_${fn.name}(${signature}) public {\n` +
        `        // TODO: bound fuzzed inputs to realistic ranges before calling, e.g.:\n` +
        `        // ${names[0] ?? 'x'} = bound(${names[0] ?? 'x'}, 0, type(uint96).max);\n` +
        `        try ${instanceVar}.${fn.name}(${callArgs}) {\n` +
        `            // TODO: assert invariants that must hold after a successful call\n` +
        `        } catch {\n` +
        `            // TODO: confirm this input SHOULD revert; if not, that's a finding\n` +
        `        }\n` +
        `    }`
    );
  }

  const skippedComment =
    skippedFunctions.length > 0
      ? `\n    // Skipped (non-elementary params, needs a manual fuzz harness): ${skippedFunctions.join(', ')}\n`
      : '';

  const content =
    `// SPDX-License-Identifier: MIT\n` +
    `pragma solidity ^0.8.19;\n\n` +
    `import {Test} from "forge-std/Test.sol";\n` +
    `import {${contract.name}} from "${importPath}";\n\n` +
    `/// Auto-generated by auditkit fuzz. Fill in setUp() constructor args and\n` +
    `/// the TODOs before relying on this -- it is a starting scaffold, not a\n` +
    `/// finished test suite.\n` +
    `contract ${contract.name}FuzzTest is Test {\n` +
    `    ${contract.name} internal ${instanceVar};\n\n` +
    `    function setUp() public {\n` +
    `        ${instanceVar} = new ${contract.name}(${ctorArgsComment});\n` +
    `    }\n` +
    skippedComment +
    `\n${testBlocks.join('\n\n')}\n` +
    `}\n`;

  mkdirSync(dirname(outPath), { recursive: true });
  await Bun.write(outPath, content);

  return { outPath, contractName: contract.name, fuzzedFunctions, skippedFunctions };
}
